name: Sync Fork

on:
  schedule:
    - cron: '*/15 * * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync Upstream Changes
        uses: tgymnich/fork-sync@v1.8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: sm-monirulislam/SM-Live-TV
          upstream_branch: main
          target_branch: main